project:
  type: website

website:
  title: "Visual-Analytics-Applications"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Exercise 1"
          href: "Hands-on_Ex/Ex01/Ex01.html"
        - text: "Exercise 2"
          href: "Hands-on_Ex/Ex02/Ex02.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Exercise 1"
          href: "Take-home_Ex/Ex01/Take-home_Ex01.html"
        - text: "Exercise 2"
          href: "Take-home_Ex/Ex02/Take-home_Ex02.html"
    - text: "In-class Exercise"
      menu: 
        - text: "Exercise 3"
          href: "In-class_Ex/Ex03/In-class_Ex03.html"
        - text: "Exercise 4"
          href: "In-class_Ex/Ex04/In-class_Ex04.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-depth: 3
    toc-title: Table of Contents
    number-sections: true
    link-external-icon: true
editor: visual

