project:
  type: website

website:
  title: "Visual-Analytics-Applications"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Exercise 1"
            href: "Hands-on_Ex/Ex01/Ex01.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

